plugins {
    id 'java'
    id "org.jetbrains.intellij.platform" version "2.13.1"
}

group = 'com.mzyupc'
version = '1.3.2'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

repositories {
    mavenCentral()
    maven { url = 'https://plugins.gradle.org/m2/' }
    intellijPlatform {
        defaultRepositories()
      }
}

dependencies {
    // 调试插件的 IDEA 版本
    intellijPlatform {
        intellijIdea("2026.1.5")
//        intellijIdea("2024.2")

        bundledPlugin("com.intellij.java")

        pluginVerifier()
        zipSigner()
    }

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.8.1'

    // jedis
    implementation ("redis.clients:jedis:5.2.0") {
        exclude group: "org.slf4j"
    }

    implementation 'com.github.mwiede:jsch:0.2.21'

    // lombok
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'
}

patchPluginXml {
    // 声明插件适用的版本
    sinceBuild = '242'
    untilBuild = '261.*'
    changeNotes = """
      1.3.2<br>
      <ul>
          <li>Upgraded the Java target to 21.</li>
          <li>Updated compatibility to IntelliJ IDEA 2024.2 through 2026.1.</li>
      </ul>
      """
}
test {
    useJUnitPlatform()
}

intellijPlatform {
    buildSearchableOptions = false

    pluginVerification {
        ides {
            recommended()
        }
    }
}
