bind 0.0.0.0
protected-mode no
port 0
tls-port 6380
tls-cert-file /certs/redis-server.crt
tls-key-file /certs/redis-server.key
tls-ca-cert-file /certs/ca.crt
tls-auth-clients no
requirepass redis-tls-pass
appendonly no
loglevel notice

